namespace Camtify.Tests.Common.AutoFixture.Attributes;

/// <summary>
/// AutoData attribute configured with Camtify domain customizations.
/// Use this attribute for parameterized tests with auto-generated domain objects.
/// </summary>
/// <example>
/// <code>
/// [Theory, CamtifyAutoData]
/// public void Test_WithAutoGeneratedIban(Iban iban)
/// {
///     iban.CountryCode.ShouldNotBeNullOrEmpty();
/// }
/// </code>
/// </example>
public class CamtifyAutoDataAttribute : AutoDataAttribute
{
    public CamtifyAutoDataAttribute()
        : base(() => new Fixture().Customize(new CamtifyCustomization()))
    {
    }
}
